const _skill = [
  {
    category: 'Developer',
    id: 'developer',
    items: [
      {
        role: 'Programmer',
        skill: [
          'Programming (PROG)',
          'Database Design (DBDS)',
          'Systems and Software Life Cycle Engineering (SLEN)',
          'Release and Deployment (RELM)',
          'Testing (TEST)',
          'Software Design (SWDN)',
          'Data Modelling and Design (DTAN)',
          'Information Security (SCTY)',
          'Quality Assurance (QUAS)',
          'Specialist Advice (TECH)',
        ],
      },
      {
        role: 'CX Designer',
        skill: [
          'User Experience Design (HCEV)',
          'User Experience Analysis (UNAN)',
          'User Experience Evaluation (USEV)',
          'User Research (URCH)',
          'Specialist Advice (TECH)',
        ],
      },
      {
        role: 'Patch Engineer',
        skill: [
          'Information Security (SCTY)',
          'Security Administration (SCAD)',
          'Penetration Testing (PENT)',
          'Programming (PROG)',
          'Specialist Advice (TECH)',
        ],
      },
    ],
  },
  {
    category: 'IT Analyst',
    id: 'it-analyst',
    items: [
      {
        role: 'SAD',
        skill: [
          'Programming (PROG)',
          'Software Design (SWDN)',
          'Database Design (DBDS)',
          'Systems Design (DESN)',
          'Requirements Definition & Management (REQM)',
          'Quality Assurance (QUAS)',
          'Testing (TEST)',
          'Release and Deployment (RELM)',
          'Change Management (CHMG)',
          'Systems Integration and Building (SINT)',
          'Software Configuration (PORT)',
          'Data Modelling and Design (DTAN)',
          'Project Management (PRMG)',
          'Content Authoring (INCA)',
          'Information Security (SCTY)',
          'Capacity Management (CPMG)',
          'High-Performance Computing (HPCC)',
          'Specialist Advice (TECH)',
        ],
      },
      {
        role: 'QA Analyst',
        skill: [
          'Quality Assurance (QUAS)',
          'Service Acceptance (SEAC)',
          'Testing (TEST)',
          'Quality Management (QUMG)',
          'Measurement (MEAS)',
          'Requirements Definition & Management (REQM)',
          'Information Security (SCTY)',
          'Project Management (PRMG)',
          'Risk Management (BURM)',
        ],
      },
      {
        role: 'Problem Analyst',
        skill: [
          'Problem Management (PBMG)',
          'Configuration Management (CFMG)',
          'Availability Management (AVMT)',
          'Systems Integration and Building (SINT)',
          'Security Administration (SCAD)',
          'Change Management (CHMG)',
          'Release and Deployment (RELM)',
          'IT Infrastructure (ITOP)',
          'Software Configuration (PORT)',
          'Service Level Management (SLMO)',
        ],
      },
      {
        role: 'Scrum Master',
        skill: [
          'Programming (PROG)',
          'Project Management (PRMG)',
          'Systems and Software Life Cycle Engineering (SLEN)',
          'Requirements Definition & Management (REQM)',
          'Stakeholder Relationship Management (RLMT)',
          'Methods and Tools (METL)',
          'Release and Deployment (RELM)',
          'User Experience Evaluation (USEV)',
          'Performance Management (PEMT)',
          'Specialist Advice (TECH)',
        ],
      },
      {
        role: 'Business Analyst',
        skill: [
          'Requirements Definition & Management (REQM)',
          'Stakeholder Relationship Management (RLMT)',
          'Software Design (SWDN)',
          'Business Process Improvement (BPRE)',
          'Business Modelling (BSMO)',
          'Feasibility Assessment (FEAS)',
          'Risk Management (BURM)',
          'Product Management (PROD)',
          'Specialist Advice (TECH)',
        ],
      },
      {
        role: 'Performance Engineer',
        skill: [
          'Measurement (MEAS)',
          'Service Level Management (SLMO)',
          'Availability Management (AVMT)',
          'Capacity Management (CPMG)',
          'Continuity Management (COPL)',
          'Testing (TEST)',
          'Specialist Advice (TECH)',
        ],
      },
      {
        role: 'Data Analyst',
        skill: [
          'Programming (PROG)',
          'Data Visualization (VISL)',
          'Data Engineering (DENG)',
          'Data Science (DATS)',
          'Data Management (DATM)',
          'Business Intelligence (BINT)',
        ],
      },
      {
        role: 'Data Scientist',
        skill: [
          'Programming (PROG)',
          'Data Science (DATS)',
          'Machine Learning (MLNG)',
          'Data Visualization (VISL)',
          'Data Engineering (DENG)',
        ],
      },
      {
        role: 'Data Engineer',
        skill: [
          'Programming (PROG)',
          'Data Engineering (DENG)',
          'Data Management (DATM)',
          'Data Visualization (VISL)',
        ],
      },
    ],
  },
  {
    category: 'Tester',
    id: 'tester',
    items: [
      {
        role: 'QA Tester',
        skill: [
          'Testing (TEST)',
          'Acceptance Testing (BPTS)',
          'Methods and Tools (METL)',
          'Quality Assurance (QUAS)',
          'Requirements Definition & Management (REQM)',
          'Penetration Testing (PENT)',
          'Risk Management (BURM)',
          'Project Management (PRMG)',
        ],
      },
    ],
  },
  // {
  //   category: 'Manager',
  //   id: 'manager',
  //   items: [
  //     {
  //       role: 'Product Manager',
  //       skill: [
  //         'Product Management (PROD)',
  //         'User Experience Evaluation (USEV)',
  //         'Business Process Improvement (BPRE)',
  //         'Innovation (INOV)',
  //         'Business Modelling (BSMO)',
  //         'Requirements Definition & Management (REQM)',
  //         'User Experience Analysis (UNAN)',
  //         'User Research (URCH)',
  //         'Demand Management (DEMM)',
  //         'Stakeholder Relationship Management (RLMT)',
  //         'Acceptance Testing (BPTS)',
  //         'Change Implementation Planning and Management (CIPM)',
  //         'Specialist Advice (TECH)',
  //       ],
  //     },
  //     {
  //       role: 'Project Manager',
  //       skill: [
  //         'Project Management (PRMG)',
  //         'Change Implementation Planning and Management (CIPM)',
  //         'Requirements Definition & Management (REQM)',
  //         'Stakeholder Relationship Management (RLMT)',
  //         'Benefits Management (BENM)',
  //         'Risk Management (BURM)',
  //         'Portfolio Programme and Project Support (PROF)',
  //         'Specialist Advice (TECH)',
  //       ],
  //     },
  //   ],
  // },
  {
    category: 'Engineer',
    id: 'engineer',
    items: [
      {
        role: 'System Engineer',
        skill: [
          'Incident Management (USUP)',
          'Service Level Management (SLMO)',
          'Availability Management (AVMT)',
          'Measurement (MEAS)',
          'Configuration Management (CFMG)',
          'Systems Integration and Building (SINT)',
          'Release and Deployment (RELM)',
          'Change Management (CHMG)',
          'Problem Management (PBMG)',
          'Software Configuration (PORT)',
          'IT Infrastructure (ITOP)',
          'Security Administration (SCAD)',
          'Specialist Advice (TECH)',
        ],
      },
      {
        role: 'DevOps Engineer',
        skill: [
          'Release and Deployment (RELM)',
          'Software Configuration (PORT)',
          'Methods and Tools (METL)',
          'Systems Integration and Building (SINT)',
          'Configuration Management (CFMG)',
          'Change Management (CHMG)',
          'IT Infrastructure (ITOP)',
          'Security Administration (SCAD)',
          'Availability Management (AVMT)',
          'Programming (PROG)',
          'Specialist Advice (TECH)',
        ],
      },
      {
        role: 'Database Administrator',
        skill: [
          'Database Administration (DBAD)',
          'Availability Management (AVMT)',
          'Capacity Management (CPMG)',
          'Incident Management (USUP)',
          'Problem Management (PBMG)',
          'Configuration Management (CFMG)',
          'Security Administration (SCAD)',
          'Specialist Advice (TECH)',
        ],
      },
    ],
  },
  {
    category: 'IT General',
    id: 'it-general',
    items: [
      {
        role: 'IT Human Capital',
        skill: [
          'Resourcing (RESC)',
          'Performance Management (PEMT)',
          'Learning Design and Development (TMCR)',
          'Professional Development (PDSV)',
          'Competency Assessment (LEDA)',
          'Specialist Advice (TECH)',
        ],
      },
      {
        role: 'Liaison Officer',
        skill: [
          'Content Authoring (INCA)',
          'Content Publishing (ICPM)',
          'Knowledge Management (KNOW)',
          'Methods and Tools (METL)',
          'Application support (ASUP)',
          'Enterprise IT Governance (GOVN)',
          'Asset management (ASMG)',
          'Change Management (CHMG)',
          'Portfolio Programme and Project Support (PROF)',
        ],
      },
      {
        role: 'Liaison Audit',
        skill: [
          'Enterprise IT Governance (GOVN)',
          'Information Governance (IRMG)',
          'Risk Management (BURM)',
          'Stakeholder Relationship Management (RLMT)',
          'Audit (AUDT)',
          'Information Security (SCTY)',
          'Quality Management (QUMG)',
          'Measurement (MEAS)',
          'Specialist Advice (TECH)',
        ],
      },
      {
        role: 'IT Procurement',
        skill: [
          'Sourcing (SORC)',
          'Contract Management (ITCM)',
          'Supplier Management (SUPP)',
          'Service Level Management (SLMO)',
          'Enterprise IT Governance (GOVN)',
          'Risk Management (BURM)',
          'Information Assurance (INAS)',
          'Information Governance (IRMG)',
        ],
      },
      {
        role: 'IT Governance',
        skill: [
          'Enterprise IT Governance (GOVN)',
          'Risk Management (BURM)',
          'Information Assurance (INAS)',
          'Information Governance (IRMG)',
        ],
      },
    ],
  },
  {
    category: 'IT Support',
    id: 'it-support',
    items: [
      {
        role: 'Operator',
        skill: [
          'Measurement (MEAS)',
          'Application Support (ASUP)',
          'Incident Management (USUP)',
          'Problem Management (PBMG)',
          'Service Level Management (SLMO)',
        ],
      },
      {
        role: 'Technical Support',
        skill: [
          'Application Support (ASUP)',
          'Incident Management (USUP)',
          'IT Infrastructure (ITOP)',
          'Problem Management (PBMG)',
          'Security Administration (SCAD)',
          'Systems Integration and Building (SINT)',
        ],
      },
    ],
  },
]

export default _skill
